service: test-slack-bot

plugins:
  - serverless-pseudo-parameters
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: non-linux
    slim: true

provider:
  name: aws
  runtime: python3.8
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  versionFunctions: false

  environment:
    BOT_TOKEN: ${file(config.${self:provider.stage}.yaml):BOT_TOKEN}

package:
  exclude:
    - .git/**
    - venv/**

functions:
  processMessage:
    handler: src.handlers.messages.process_message
    events:
      - http:
          path: message
          method: post
  processInteractivity:
    handler: src.handlers.interactivities.process_interactivity
    events:
      - http:
          path: interactivity
          method: post
