service: test-slack-bot

plugins:
  - serverless-pseudo-parameters
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: non-linux
    slim: true

provider:
  name: aws
  runtime: python3.8
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  versionFunctions: false

  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:Query"
        - "dynamodb:UpdateItem"
        - "dynamodb:DescribeTable"
        - "dynamodb:DeleteItem"
      Resource:
        - Fn::GetAtt: [ userVacationTable, Arn ]

  environment:
    BOT_TOKEN: ${file(configs/config.${self:provider.stage}.yaml):BOT_TOKEN}
    GENERAL_CHANNEL_ID: ${file(configs/config.${self:provider.stage}.yaml):GENERAL_CHANNEL_ID}
    USER_VACATION_TABLE_NAME:
      Ref: userVacationTable

package:
  exclude:
    - .git/**
    - venv/**
    - node_modules/**

functions:
  processMessage:
    handler: src.handlers.messages.process_message
    package:
      artifact:
    events:
      - http:
          path: message
          method: post
  processInteractivity:
    handler: src.handlers.interactivities.process_interactivity
    package:
      artifact:
    events:
      - http:
          path: interactivity
          method: post
  notifyAboutNewVacation:
    handler: src.handlers.notifications.notify_about_new_vacation
    package:
      artifact:
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt: [ userVacationTable, StreamArn ]


resources:
  Resources:
    userVacationTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_IMAGE
